version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '07:00'
      timezone: Japan
    open-pull-requests-limit: 10
    reviewers:
      - kzhrk
    assignees:
      - kzhrk
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
