name: test
on: [pull_request_target]

jobs:
  actions-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prepare node
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Save pnpm case
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: test-v1-pnpm-${{ hashFiles('**\pnpm-lock.yaml') }}
          restore-keys: |
            test-v1-pnpm-
      - name: Install Dependencies
        run: pnpm install
      - name: Run test
        run: pnpm test
